// showcases/vue-showcase/src/components/input/Input.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/input.json";
import {
	DBInput,
	LabelVariantType,
	ValueLabelType
} from "../../../../../output/vue/src";

const getDataList = (
	variant?: LabelVariantType
): string[] | ValueLabelType[] => {
	if (variant === "floating") {
		return ["Test 1", "Test 2"];
	}

	return [
		{ value: "test1", label: "Test 1" },
		{ value: "test2", label: "Test 2" }
	];
};
</script>

<template>
	<DefaultComponent title="DBInput" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInput
				:variant="exampleProps.variant"
				:label="exampleProps.label"
				:message="exampleProps.message"
				:placeholder="exampleName"
				:minLength="exampleProps.minLength"
				:required="exampleProps.required"
				:type="exampleProps.type"
				:disabled="exampleProps.disabled"
				:readOnly="exampleProps.readOnly"
				:value="exampleProps.value"
				:icon="exampleProps.icon"
				:iconAfter="exampleProps.iconAfter"
				:dataList="
					exampleProps.dataList
						? getDataList(exampleProps.variant)
						: undefined
				"
			></DBInput>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/input/input.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/input.json';
import { DefaultComponent } from '../default.component';
import {
	DBInput,
	LabelVariantType,
	ValueLabelType
} from '../../../../../../output/angular/src';

@Component({
	selector: 'app-input',
	templateUrl: './input.component.html',
	imports: [DefaultComponent, DBInput],
	standalone: true
})
export class InputComponent {
	variants = defaultComponentVariants;

	getDataList = (variant?: LabelVariantType): string[] | ValueLabelType[] => {
		if (variant === 'floating') {
			return ['Test 1', 'Test 2'];
		}

		return [
			{ value: 'test1', label: 'Test 1' },
			{ value: 'test2', label: 'Test 2' }
		];
	};
}

<app-default-component
	title="DBInput"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-input
			[variant]="exampleProps.variant"
			[label]="exampleProps.label"
			[message]="exampleProps.message"
			[placeholder]="exampleName"
			[minLength]="exampleProps.minLength"
			[required]="exampleProps.required"
			[type]="exampleProps.type"
			[disabled]="exampleProps.disabled"
			[value]="exampleProps.value"
			[icon]="exampleProps.icon"
			[iconAfter]="exampleProps.iconAfter"
			[dataList]="
				exampleProps.dataList
					? getDataList(exampleProps.variant)
					: undefined
			"
		></db-input>
	</ng-template>
</app-default-component>
