// showcases/vue-showcase/src/components/form/Checkboxes.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import FormWrapper from "./FormWrapper.vue";
import { DBCheckbox } from "../../../../../output/vue/src";
import { ref } from "vue";

const plain = ref(true);
const vModel = ref(true);
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBCheckbox
			name="checkbox-1"
			@change="plain = $event.target.checked"
			:checked="plain"
		>
			Plain
		</DBCheckbox>
		<DBCheckbox name="checkbox-1" v-model:checked="vModel">
			VModel
		</DBCheckbox>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/checkboxes/checkboxes.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { WrapperComponent } from '../wrapper/wrapper.component';
import { DBCheckbox, DBInput } from '../../../../../../../output/angular/src';
import { environment } from '../../../../environments/environment';

@Component({
	selector: 'app-checkboxes',
	standalone: true,
	imports: environment.webComponents
		? [WrapperComponent, FormsModule, ReactiveFormsModule]
		: [WrapperComponent, DBCheckbox, FormsModule, ReactiveFormsModule],
	templateUrl: './checkboxes.component.html',
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class CheckboxesComponent {
	plain = true;
	ngModel = true;
	formControl: FormControl = new FormControl(true);
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-form-wrapper
	[plain]="plain"
	[model]="ngModel"
	[control]="formControl.value"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-checkbox
			[checked]="plain"
			(change)="plain = $event.target.checked"
			name="checkbox"
			label="Plain"
		></db-checkbox>
		<db-checkbox
			[(ngModel)]="ngModel"
			name="checkbox"
			label="ngModel"
		></db-checkbox>
		<db-checkbox
			[formControl]="formControl"
			name="checkbox"
			label="formControl"
		></db-checkbox>
	</fieldset>
</app-form-wrapper>
