// showcases/vue-showcase/src/components/form/Selects.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import FormWrapper from "./FormWrapper.vue";
import { DBSelect } from "../../../../../output/vue/src";
import { ref } from "vue";

const plain = ref("combobox-2");
const vModel = ref("combobox-2");
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBSelect
			:value="plain"
			label="Plain"
			@change="plain = $event.target.value"
		>
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</DBSelect>
		<DBSelect label="VModel" v-model:value="vModel">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</DBSelect>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/selects/selects.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { WrapperComponent } from '../wrapper/wrapper.component';
import { DBSelect, DBTextarea } from '../../../../../../../output/angular/src';
import { environment } from '../../../../environments/environment';

@Component({
	selector: 'app-selects',
	standalone: true,
	imports: environment.webComponents
		? [WrapperComponent, FormsModule, ReactiveFormsModule]
		: [WrapperComponent, DBSelect, FormsModule, ReactiveFormsModule],
	templateUrl: './selects.component.html',
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class SelectsComponent {
	plain = 'combobox-2';
	ngModel = 'combobox-2';
	formControl: FormControl = new FormControl('combobox-2');
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-form-wrapper
	[plain]="plain"
	[model]="ngModel"
	[control]="formControl.value"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-select
			label="Plain"
			[value]="plain"
			(change)="plain = $event.target.value"
		>
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</db-select>
		<db-select label="ngModel" [(ngModel)]="ngModel">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</db-select>
		<db-select label="formControl" [formControl]="formControl">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</db-select>
	</fieldset>
</app-form-wrapper>
