// showcases/vue-showcase/src/components/tag/Tag.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tag.json";
import { DBTag } from "../../../../../output/vue/src";

const showAlert = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName || "");
};
</script>

<template>
	<DefaultComponent title="DBTag" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<i class="line-break" v-if="exampleProps?.lineBreak" />
			<DBTag
				v-if="!exampleProps?.lineBreak"
				:semantic="exampleProps?.semantic"
				:icon="exampleProps?.icon"
				:noText="exampleProps?.noText"
				:behaviour="exampleProps?.behaviour"
				:emphasis="exampleProps?.emphasis"
				:showIcon="exampleProps?.showIcon"
				:showCheckState="exampleProps?.showCheckState"
				:overflow="exampleProps?.overflow"
				:removeButton="exampleProps?.removeButton"
				@remove="showAlert(exampleName)"
			>
				<div
					v-if="exampleProps?.content"
					slot="content"
					class="default-content-slot"
				>
					Swap Slot
				</div>

				<button v-if="exampleProps?.component === 'button'">
					{{ exampleName }}
				</button>
				<a v-if="exampleProps?.component === 'link'" href="#">
					{{ exampleName }}
				</a>
				<label v-if="exampleProps?.component === 'checkbox'">
					<input
						type="checkbox"
						:disabled="exampleProps?.disabled"
						:checked="exampleProps?.checked"
					/>
					{{ exampleName }}
				</label>

				<label v-if="exampleProps?.component === 'radio'">
					<input
						type="radio"
						:checked="exampleProps?.checked"
						:name="exampleProps?.identifier"
					/>
					{{ exampleName }}
				</label>
				<template
					v-if="
						exampleProps?.component !== 'button' &&
						exampleProps?.component !== 'link' &&
						exampleProps?.component !== 'checkbox' &&
						exampleProps?.component !== 'radio' &&
						!exampleProps?.overflow
					"
				>
					{{ exampleName }}
				</template>
				<template
					v-if="
						exampleProps?.component !== 'button' &&
						exampleProps?.component !== 'link' &&
						exampleProps?.component !== 'checkbox' &&
						exampleProps?.component !== 'radio' &&
						exampleProps?.overflow
					"
				>
					<span>{{ exampleName }}</span>
				</template>
			</DBTag>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tag/index.tsx
import { useState } from 'react';
import { DBTag } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/tag.json';
import { type DBTagProps } from '../../../../../output/react/src/components/tag/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getTag = ({
	semantic,
	disabled,
	children,
	icon,
	overflow,
	noText,
	behaviour,
	emphasis,
	removeButton,
	checked,
	component,
	identifier,
	content,
	showCheckState,
	lineBreak,
	showIcon
}: DBTagProps & {
	checked?: boolean;
	component?: 'button' | 'link' | 'radio' | 'checkbox';
	identifier?: string;
	lineBreak?: boolean;
}) => {
	const [checkedState, setCheckedState] = useState<boolean>(checked ?? false);

	if (lineBreak) {
		return <i className="line-break" />;
	}

	return (
		<DBTag
			semantic={semantic}
			icon={icon}
			noText={noText}
			behaviour={behaviour}
			emphasis={emphasis}
			overflow={overflow}
			removeButton={removeButton}
			showCheckState={showCheckState}
			showIcon={showIcon}
			content={
				content ? (
					<div className="default-content-slot">Swap Slot</div>
				) : undefined
			}
			onRemove={() => {
				// eslint-disable-next-line no-alert
				alert(children.toString());
			}}>
			{component === 'button' && <button>{children}</button>}
			{component === 'link' && <a href="#">{children}</a>}
			{component === 'checkbox' && (
				<label>
					<input
						type="checkbox"
						checked={checkedState}
						disabled={disabled}
						onChange={(event) => {
							setCheckedState(event.target.checked);
						}}
					/>
					{children}
				</label>
			)}
			{component === 'radio' && (
				<label>
					<input type="radio" checked={checked} name={identifier} />
					{children}
				</label>
			)}

			{!component && !overflow && <>{children}</>}
			{!component && overflow && <span>{children}</span>}
		</DBTag>
	);
};

const TagComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBTag"
			variants={getVariants(
				defaultComponentVariants,
				getTag,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default TagComponent;
