// showcases/vue-showcase/src/components/switch/Switch.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/switch.json";
import { DBSwitch, DBInfotext } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBSwitch" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSwitch
				:visualAid="exampleProps?.visualAid"
				:checked="exampleProps?.checked"
				:disabled="exampleProps?.disabled"
				:variant="exampleProps?.variant"
				:size="exampleProps?.size"
				:emphasis="exampleProps?.emphasis"
				:icon="exampleProps?.icon"
				:iconAfter="exampleProps?.iconAfter"
			>
				{{ exampleName }}
			</DBSwitch>
			<DBInfotext
				v-if="exampleProps?.variant === 'hidden'"
				semantic="informational"
				icon="none"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/switch/switch.component.ts
import { Component } from '@angular/core';
import { DefaultComponent } from '../default.component';
import defaultComponentVariants from '../../../../../shared/switch.json';
import { DBSwitch } from '../../../../../../output/angular/src/components/switch';
import { DBInfotext } from '../../../../../../output/angular/src/components/infotext';

@Component({
	selector: 'app-switch',
	templateUrl: './switch.component.html',
	imports: [DefaultComponent, DBSwitch, DBInfotext],
	standalone: true
})
export class SwitchComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBSwitch"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-switch
			[visualAid]="exampleProps.visualAid"
			[checked]="exampleProps.checked"
			[disabled]="exampleProps.disabled"
			[variant]="exampleProps.variant"
			[size]="exampleProps.size"
			[emphasis]="exampleProps.emphasis"
			[icon]="exampleProps.icon"
			[iconAfter]="exampleProps.iconAfter"
		>
			{{ exampleName }}
		</db-switch>
		@if (exampleProps.variant === "hidden") {
			<DBInfotext semantic="informational" icon="none">
				{{ exampleName }}
			</DBInfotext>
		}
	</ng-template>
</app-default-component>
