// showcases/vue-showcase/src/components/accordion-item/AccordionItem.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/accordion-item.json";
import { DBAccordionItem } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent
		title="DBAccordionItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBAccordionItem
				:headlinePlain="exampleProps?.headlinePlain"
				:disabled="exampleProps?.disabled"
				:default-open="exampleProps?.open"
			>
				{{ exampleName }}
			</DBAccordionItem>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/accordion-item/accordion-item.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/accordion-item.json';
import { DBAccordionItem } from '../../../../../../output/angular/src';
import { DefaultComponent } from '../default.component';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-accordion-item',
	templateUrl: './accordion-item.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBAccordionItem],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AccordionItemComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBAccordionItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-accordion-item
			[headlinePlain]="exampleProps?.headlinePlain"
			[disabled]="exampleProps?.disabled"
			[defaultOpen]="exampleProps?.open"
		>
			{{ exampleName }}
		</db-accordion-item>
	</ng-template>
</app-default-component>
