// showcases/vue-showcase/src/components/infotext/Infotext.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/infotext.json";
import { DBInfotext } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBInfotext" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext
				:size="exampleProps?.size"
				:semantic="exampleProps?.semantic"
				:icon="exampleProps?.icon"
				:showIcon="exampleProps?.showIcon"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/infotext/infotext.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/infotext.json';
import { DefaultComponent } from '../default.component';
import { DBInfotext } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-infotext',
	templateUrl: './infotext.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBInfotext],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class InfotextComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBInfotext"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-infotext
			[size]="exampleProps?.size"
			[semantic]="exampleProps?.semantic"
			[icon]="exampleProps?.icon"
			[showIcon]="exampleProps?.showIcon"
		>
			{{ exampleName }}
		</db-infotext>
	</ng-template>
</app-default-component>
