// showcases/vue-showcase/src/components/tab-item/TabItem.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-item.json";
import { DBTabItem, DBTabList } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTabItem" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTabList
				><DBTabItem
					:active="exampleProps?.active"
					:noText="exampleProps?.noText"
					:icon="exampleProps?.icon"
					:iconAfter="exampleProps?.iconAfter"
					:disabled="exampleProps?.disabled"
				>
					{{ exampleName }}
				</DBTabItem>
			</DBTabList>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/tab-item/tab-item.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tab-item.json';
import { DefaultComponent } from '../default.component';
import { DBTabItem, DBTabList } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-tab',
	templateUrl: './tab-item.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBTabItem, DBTabList],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	standalone: true
})
export class TabItemComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBTabItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
		><db-tab-list>
			<db-tab-item
				[active]="exampleProps?.active"
				[noText]="exampleProps?.noText"
				[icon]="exampleProps?.icon"
				[iconAfter]="exampleProps?.iconAfter"
				[disabled]="exampleProps?.disabled"
			>
				{{ exampleName }}
			</db-tab-item>
		</db-tab-list>
	</ng-template>
</app-default-component>
