// showcases/react-showcase/src/components/button/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/button.json';
import { type DBButtonProps } from '../../../../../output/react/src/components/button/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getButton = ({
	variant,
	state,
	size,
	noText,
	icon,
	width,
	disabled,
	children,
	type,
	showIcon
}: DBButtonProps) => (
	<DBButton
		variant={variant}
		state={state}
		size={size}
		noText={noText}
		icon={icon}
		disabled={disabled}
		width={width}
		showIcon={showIcon}
		onClick={() => {
			// eslint-disable-next-line no-alert
			alert(children.toString());
		}}
		type={type}>
		{children}
	</DBButton>
);

const ButtonComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBButton"
			variants={getVariants(
				defaultComponentVariants,
				getButton,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default ButtonComponent;

// showcases/vue-showcase/src/components/button/Button.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/button.json";
import { DBButton } from "../../../../../output/vue/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent title="DBButton" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton
				:variant="exampleProps?.variant"
				:size="exampleProps?.size"
				:icon="exampleProps?.icon"
				:noText="exampleProps?.noText"
				:showIcon="exampleProps?.showIcon"
				:disabled="exampleProps?.disabled"
				:width="exampleProps?.width"
				@click="log(exampleName)"
			>
				{{ exampleName }}
			</DBButton>
		</template>
	</DefaultComponent>
</template>
