// showcases/angular-showcase/src/app/components/button/button.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/button.json';
import { DefaultComponent } from '../default.component';
import { DBButton } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-button',
	templateUrl: './button.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBButton],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class ButtonComponent {
	variants = defaultComponentVariants;

	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBButton"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-button
			[variant]="exampleProps?.variant"
			[size]="exampleProps?.size"
			[icon]="exampleProps?.icon"
			[noText]="exampleProps?.noText"
			[showIcon]="exampleProps?.showIcon"
			[disabled]="exampleProps?.disabled"
			[width]="exampleProps?.width"
			(click)="showAlert(exampleName)"
		>
			{{ exampleName }}
		</db-button>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/button/Button.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/button.json";
import { DBButton } from "../../../../../output/vue/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent title="DBButton" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton
				:variant="exampleProps?.variant"
				:size="exampleProps?.size"
				:icon="exampleProps?.icon"
				:noText="exampleProps?.noText"
				:showIcon="exampleProps?.showIcon"
				:disabled="exampleProps?.disabled"
				:width="exampleProps?.width"
				@click="log(exampleName)"
			>
				{{ exampleName }}
			</DBButton>
		</template>
	</DefaultComponent>
</template>
