// showcases/angular-showcase/src/app/components/header/header.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/header.json';
import { DefaultComponent } from '../default.component';
import {
	DBBrand,
	DBButton,
	DBHeader,
	DBLink,
	DBNavigation,
	DBNavigationItem,
	MetaNavigationDirective,
	NavigationContentDirective,
	NavigationDirective,
	SecondaryActionDirective
} from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-header',
	templateUrl: './header.component.html',
	imports: environment.webComponents
		? [
				DefaultComponent,
				DBHeader,
				DBNavigation,
				DBNavigationItem,
				SecondaryActionDirective,
				NavigationDirective,
				MetaNavigationDirective,
				NavigationContentDirective
			] // TODO: Remove DBHeader,DBNavigation,DBNavigationItem,SecondaryActionDirective,NavigationDirective,MetaNavigationDirective,NavigationContentDirective after stencil component works
		: [
				DefaultComponent,
				DBBrand,
				DBButton,
				DBHeader,
				DBLink,
				DBNavigation,
				DBNavigationItem,
				SecondaryActionDirective,
				NavigationDirective,
				MetaNavigationDirective,
				NavigationContentDirective
			],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class HeaderComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBHeader"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-header
			[width]="exampleProps?.width"
			[forceMobile]="exampleProps?.forceMobile"
		>
			<db-brand brand>
				@if (!exampleProps?.example || exampleProps?.withName) {
					DBHeader
				}
			</db-brand>
			<ng-container *dbNavigation>
				@if (!exampleProps?.example || exampleProps?.withNavigation) {
					<db-navigation [attr.aria-label]="exampleName">
						<db-navigation-item icon="x_placeholder">
							<a href="#" *dbNavigationContent
								>{{ exampleName }}
							</a>
						</db-navigation-item>
						<db-navigation-item [disabled]="true">
							<a href="#" *dbNavigationContent
								>{{ exampleName }} disabled
							</a>
						</db-navigation-item>
					</db-navigation>
				}
			</ng-container>
			<ng-container *dbMetaNavigation>
				@if (!exampleProps?.example) {
					<db-link href="#">Imprint</db-link>
					<db-link href="#">Help</db-link>
				}
			</ng-container>
			<ng-container primary-action>
				@if (!exampleProps?.example) {
					<db-button
						icon="magnifying_glass"
						variant="ghost"
						[noText]="true"
						>Search</db-button
					>
				}
			</ng-container>
			<ng-container *dbSecondaryAction>
				@if (!exampleProps?.example) {
					<db-button
						icon="x_placeholder"
						variant="ghost"
						[noText]="true"
					>
						Profile
					</db-button>
					<db-button
						icon="x_placeholder"
						variant="ghost"
						[noText]="true"
					>
						Notification
					</db-button>
					<db-button
						icon="x_placeholder"
						variant="ghost"
						[noText]="true"
					>
						Help
					</db-button>
				}
			</ng-container>
		</db-header>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/header/Header.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/header.json";
import {
	DBBrand,
	DBButton,
	DBHeader,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBHeader" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBHeader
				:width="exampleProps?.width"
				:force-mobile="exampleProps?.forceMobile"
			>
				<template v-slot:brand>
					<DBBrand>
						<template
							v-if="
								!exampleProps?.example || exampleProps?.withName
							"
						>
							DBHeader
						</template>
					</DBBrand>
				</template>
				<template
					v-if="
						!exampleProps?.example || exampleProps?.withNavigation
					"
				>
					<DBNavigation :aria-label="exampleName">
						<DBNavigationItem icon="x_placeholder">
							<a href="#">{{ exampleName }}</a>
						</DBNavigationItem>
						<DBNavigationItem :disabled="true">
							<a href="#">{{ exampleName }} disabled</a>
						</DBNavigationItem>
					</DBNavigation>
				</template>
				<template v-slot:primary-action>
					<template v-if="!exampleProps?.example">
						<DBButton
							icon="magnifying_glass"
							variant="ghost"
							:no-text="true"
						>
							Search
						</DBButton></template
					>
				</template>
				<template v-slot:secondary-action>
					<template v-if="!exampleProps?.example">
						<DBButton
							icon="x_placeholder"
							variant="ghost"
							:no-text="true"
						>
							Profile
						</DBButton>
						<DBButton
							icon="x_placeholder"
							variant="ghost"
							:no-text="true"
						>
							Notification
						</DBButton>
						<DBButton
							icon="x_placeholder"
							variant="ghost"
							:no-text="true"
						>
							Help
						</DBButton></template
					>
				</template>
				<template v-slot:meta-navigation>
					<template v-if="!exampleProps?.example">
						<DBLink href="#">Imprint</DBLink>
						<DBLink href="#">Help</DBLink></template
					>
				</template>
			</DBHeader>
		</template>
	</DefaultComponent>
</template>
