// showcases/angular-showcase/src/app/components/drawer/drawer.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/drawer.json';
import { DefaultComponent } from '../default.component';
import { DBButton, DBDrawer } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-drawer',
	templateUrl: './drawer.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBDrawer, DBButton],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class DrawerComponent {
	variants = defaultComponentVariants;
	openDrawer: string | undefined = undefined;
	toggleDrawer = (example?: string) => {
		this.openDrawer = example;
	};
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBDrawer"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-button (click)="toggleDrawer(exampleName)">
			Open: {{ exampleName }}
		</db-button>
		<db-drawer
			[backdrop]="exampleProps?.backdrop"
			[rounded]="exampleProps?.rounded"
			[width]="exampleProps?.width"
			[spacing]="exampleProps?.spacing"
			[direction]="exampleProps?.direction"
			[variant]="exampleProps?.variant"
			[open]="openDrawer === exampleName"
			(onClose)="toggleDrawer(undefined)"
			(close)="toggleDrawer(undefined)"
		>
			{{ exampleName }}
		</db-drawer>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/drawer/Drawer.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import { ref } from "vue";
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/drawer.json";
import { DBDrawer, DBButton } from "../../../../../output/vue/src";

const openDrawer = ref<string | undefined>(undefined);

const toggleDrawer = (example?: string) => {
	openDrawer.value = example;
};
</script>

<template>
	<DefaultComponent title="DBDrawer" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton @click="toggleDrawer(exampleName)">
				Open: {{ exampleName }}
			</DBButton>
			<DBDrawer
				:backdrop="exampleProps?.backdrop"
				:rounded="exampleProps?.rounded"
				:width="exampleProps?.width"
				:spacing="exampleProps?.spacing"
				:direction="exampleProps?.direction"
				:variant="exampleProps?.variant"
				:open="openDrawer && openDrawer === exampleName"
				@close="toggleDrawer(undefined)"
			>
				{{ exampleName }}
			</DBDrawer>
		</template>
	</DefaultComponent>
</template>
