// showcases/vue-showcase/src/components/card/Card.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/card.json";
import { DBCard } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBCard" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCard
				:behaviour="exampleProps?.behaviour"
				:elevationLevel="exampleProps?.elevationLevel"
				:spacing="exampleProps?.spacing"
			>
				<strong>{{ exampleName }}</strong>
			</DBCard>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/card/card.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/card.json';
import { DefaultComponent } from '../default.component';
import { DBCard } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-card',
	templateUrl: './card.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBCard],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class CardComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBCard"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-card
			[behaviour]="exampleProps?.behaviour"
			[elevationLevel]="exampleProps?.elevationLevel"
			[spacing]="exampleProps?.spacing"
		>
			<strong>{{ exampleName }}</strong>
		</db-card>
	</ng-template>
</app-default-component>
