// showcases/vue-showcase/src/components/link/Link.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/link.json";
import { DBLink } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBLink" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBLink
				:variant="exampleProps?.variant"
				:href="exampleProps?.href"
				:disabled="exampleProps?.disabled"
				:size="exampleProps?.size"
				:content="exampleProps?.content"
				:showIcon="exampleProps?.showIcon"
			>
				{{ exampleName }}
			</DBLink>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/link/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBLink } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/link.json';
import { type DBLinkProps } from '../../../../../output/react/src/components/link/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getLink = ({
	href,
	variant,
	disabled,
	size,
	content,
	children,
	showIcon
}: DBLinkProps) => (
	<DBLink
		href={href}
		variant={variant}
		disabled={disabled}
		size={size}
		content={content}
		showIcon={showIcon}>
		{children}
	</DBLink>
);

const LinkComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBLink'}
			variants={getVariants(
				defaultComponentVariants,
				getLink,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default LinkComponent;
