// showcases/react-showcase/src/components/select/index.tsx
import { DBSelect } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/select.json';
import type { DBSelectProps } from '../../../../../output/react/src/components/select/model';
import { getVariants } from '../data';

const getSelect = ({
	children,
	label,
	options,
	icon,
	message,
	disabled,
	value,
	required,
	variant,
	invalid
}: DBSelectProps) => (
	<DBSelect
		label={label}
		placeholder={children}
		options={options}
		disabled={disabled}
		variant={variant}
		icon={icon}
		value={value}
		message={message}
		invalid={invalid}
		required={required}
		invalidMessage={
			invalid !== undefined || required ? 'Invalid Message' : undefined
		}
		validMessage={
			invalid !== undefined || required ? 'Valid Message' : undefined
		}>
		{children}
	</DBSelect>
);

const SelectComponent = () => {
	return (
		<DefaultComponent
			title="DBSelect"
			variants={getVariants(
				defaultComponentVariants,
				getSelect
			)}></DefaultComponent>
	);
};

export default SelectComponent;

// showcases/vue-showcase/src/components/select/Select.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/select.json";
import { DBInput, DBSelect } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="Select" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSelect
				:label="exampleProps.label"
				:placeholder="exampleName"
				:variant="exampleProps.variant"
				:options="exampleProps.options"
				:disabled="exampleProps.disabled"
				:icon="exampleProps.icon"
				:value="exampleProps.value"
				:message="exampleProps.message"
				:required="exampleProps.required"
				:invalidMessage="
					exampleProps.invalid !== undefined || exampleProps.required
						? 'Invalid Message'
						: undefined
				"
				:validMessage="
					exampleProps.invalid !== undefined || exampleProps.required
						? 'Valid Message'
						: undefined
				"
			>
				{{ exampleName }}
			</DBSelect>
		</template>
	</DefaultComponent>
</template>
