// showcases/angular-showcase/src/app/components/select/select.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/select.json';
import { DefaultComponent } from '../default.component';
import { DBSelect } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-select',
	templateUrl: './select.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBSelect]
	],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	standalone: true
})
export class SelectComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBSelect"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-select
			[label]="exampleProps?.label"
			[placeholder]="exampleName"
			[variant]="exampleProps?.variant"
			[showLabel]="exampleProps?.showLabel"
			[options]="exampleProps?.options"
			[disabled]="exampleProps?.disabled"
			[icon]="exampleProps?.icon"
			[required]="exampleProps?.required"
			[value]="exampleProps?.value"
			[message]="exampleProps?.message"
			[showMessage]="exampleProps?.showMessage"
			[invalidMessage]="exampleProps?.invalidMessage"
			[validMessage]="exampleProps?.validMessage"
			[validation]="exampleProps?.validation"
			>{{ exampleName }}</db-select
		>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/select/Select.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/select.json";
import { DBCheckbox, DBInput, DBSelect } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBSelect" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSelect
				:label="exampleProps?.label"
				:placeholder="exampleName"
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:options="exampleProps?.options"
				:disabled="exampleProps?.disabled"
				:icon="exampleProps?.icon"
				:value="exampleProps?.value"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
			>
				{{ exampleName }}
			</DBSelect>
		</template>
	</DefaultComponent>
</template>
