// showcases/angular-showcase/src/app/components/tooltip/tooltip.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tooltip.json';
import { DefaultComponent } from '../default.component';
import { DBButton, DBTooltip } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-tooltip',
	templateUrl: './tooltip.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBTooltip, DBButton],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	standalone: true
})
export class TooltipComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBTooltip"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-button>
			{{ exampleName }}
			<db-tooltip
				[width]="exampleProps?.width"
				[emphasis]="exampleProps?.emphasis"
				[placement]="exampleProps?.placement"
				[animation]="exampleProps?.animation"
				[delay]="exampleProps?.delay"
				[variant]="exampleProps?.variant"
				>{{ exampleProps?.content }}</db-tooltip
			>
		</db-button>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tooltip/Tooltip.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tooltip.json";
import { DBButton, DBTooltip } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTooltip" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton>
				{{ exampleName }}
				<DBTooltip
					:width="exampleProps?.width"
					:emphasis="exampleProps?.emphasis"
					:placement="exampleProps?.placement"
					:animation="exampleProps?.animation"
					:delay="exampleProps?.delay"
					:variant="exampleProps?.variant"
				>
					{{ exampleProps?.content }}
				</DBTooltip>
			</DBButton>
		</template>
	</DefaultComponent>
</template>
