// showcases/react-showcase/src/components/form/form-wrapper.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { type PropsWithChildren } from 'react';

const FormWrapper = ({
	children,
	uncontrolled,
	controlled
}: PropsWithChildren<{
	controlled: string | boolean;
	uncontrolled: string | boolean;
}>) => {
	return (
		<div className="form-container">
			<form>
				<fieldset>{children}</fieldset>
			</form>
			<dl data-testid="data-list">
				<dt>Controlled:</dt>
				<dd>{controlled.toString()}</dd>
				<dt>Uncontrolled:</dt>
				<dd>{uncontrolled.toString()}</dd>
			</dl>
		</div>
	);
};

export default FormWrapper;

// showcases/vue-showcase/src/components/form/FormWrapper.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
const props = defineProps(["plain", "vmodel"]);
</script>

<template>
	<div class="form-container">
		<form>
			<fieldset><slot /></fieldset>
		</form>
		<dl data-testid="data-list">
			<dt>Plain:</dt>
			<dd>{{ plain?.toString() }}</dd>
			<dt>VModel:</dt>
			<dd>{{ vmodel?.toString() }}</dd>
		</dl>
	</div>
</template>
