// showcases/react-showcase/src/components/form/index.tsx
import { useEffect, useState } from 'react';
import {
	DBButton,
	DBCheckbox,
	DBInput,
	DBRadio,
	DBSelect,
	DBTag,
	DBTextarea,
	DBAccordion,
	DBAccordionItem,
	DBTab,
	DBDivider,
	DBTabList,
	DBTabPanel,
	DBTabs
} from '../../../../../output/react/src';
import type {
	ChangeEvent,
	KeyValueType
} from '../../../../../output/react/src/shared/model';

const FormComponent = () => {
	const [input, setInput] = useState('');
	const [dateinput, setDateinput] = useState('');
	const [textarea, setTextarea] = useState('default textarea');
	const [textareaChildren, setTextareaChildren] = useState('');
	const [radio, setRadio] = useState('');
	const [select, setSelect] = useState('');
	const [tags, setTags] = useState<string[]>([]);
	const [checked, setChecked] = useState<boolean[]>([true, false]);

	const [accordionItems, setAccordionItems] = useState<KeyValueType[]>();
	const [tabsTest, setTabsTest] = useState<boolean>(false);

	useEffect(() => {
		setTimeout(() => {
			setAccordionItems([
				{ key: 'test1', value: 'Test1' },
				{ key: 'test2', value: 'Test2' },
				{ key: 'test3', value: 'Test3' }
			]);
		}, 2000);
	}, []);

	const dataList: KeyValueType[] = [
		{ key: 'test', value: 'Test' },
		{ key: 'test2' }
	];

	const handleChange1 = (event: ChangeEvent<HTMLInputElement>) => {
		setChecked([event.target.checked, event.target.checked]);
	};

	const handleChange2 = (event: ChangeEvent<HTMLInputElement>) => {
		setChecked([event.target.checked, checked[1]]);
	};

	const handleChange3 = (event: ChangeEvent<HTMLInputElement>) => {
		setChecked([checked[0], event.target.checked]);
	};

	return (
		<div className="form-container">
			<div>
				<form>
					<fieldset>
						<p>Input:</p>
						<DBInput
							label="Textinput"
							placeholder="Placeholder"
							message="Description"
							icon="account"
							name="input-name"
							value={input}
							dataList={dataList}
							onChange={(event) => {
								setInput(event.target.value);
							}}
						/>
						<p>Textarea:</p>
						<DBTextarea
							label="Textarea Controlled"
							value={textarea}
							onChange={(event) => {
								setTextarea(event.target.value);
							}}
						/>
						<DBInput
							label="Date input"
							message="Description"
							name="input-date-name"
							onChange={(event) => {
								setDateinput(event.target.value);
							}}
							type="date"
						/>
						<DBTextarea
							label="Textarea Default value"
							defaultValue="text area default value"
							onChange={(event) => {
								setTextareaChildren(event.target.value);
							}}
						/>
						<p>Radio:</p>
						<ul>
							{['X', 'Y', 'Z'].map((radioName) => (
								<li key={`radio-${radioName}`}>
									<DBRadio
										name="radio-group"
										value={radioName}
										onChange={() => {
											setRadio(radioName);
										}}>
										Radio {radioName}
									</DBRadio>
								</li>
							))}
						</ul>
						<p>Tags:</p>
						<ul>
							{['X', 'Y', 'Z'].map((tag, index) => (
								<li key={`tag-${tag}`}>
									<DBTag
										semantic={
											index === 0
												? undefined
												: 'successful'
										}
										emphasis={
											index === 2 ? 'strong' : undefined
										}>
										<DBCheckbox
											onChange={() => {
												if (tags.includes(tag)) {
													setTags(
														tags.filter(
															(t) => t !== tag
														)
													);
												} else {
													setTags([...tags, tag]);
												}
											}}>
											Tag {tag}
										</DBCheckbox>
									</DBTag>
								</li>
							))}
						</ul>
						<p>Checkbox:</p>
						<DBCheckbox
							name="checkbox"
							value="Checkbox checked"
							checked={checked[0] && checked[1]}
							indeterminate={checked[0] !== checked[1]}
							onChange={handleChange1}>
							Checkbox Indeterminate
						</DBCheckbox>
						<fieldset>
							<DBCheckbox
								name="checkbox-1"
								value="Checkbox checked"
								checked={checked[0]}
								onChange={handleChange2}>
								Checkbox
							</DBCheckbox>
							<DBCheckbox
								name="checkbox-2"
								value="Checkbox checked"
								checked={checked[1]}
								onChange={handleChange3}>
								Checkbox
							</DBCheckbox>
							<DBCheckbox
								name="checkbox-3"
								value="Irgendwas"
								defaultChecked={false}>
								DefaultChecked
							</DBCheckbox>
						</fieldset>
						<p>DBSelect:</p>
						<DBSelect
							value={select}
							label="Label"
							onChange={(event) => {
								setSelect(event.target.value);
							}}>
							<option value="test1">Test1</option>
							<option value="test2">Test2</option>
						</DBSelect>
						<p>Button:</p>
						<DBButton
							type="button"
							onClick={() => {
								setInput('reset');
							}}>
							Reset and Toggle
						</DBButton>
						<DBButton
							type="button"
							variant="brand"
							onClick={(clickEvent) => {
								// eslint-disable-next-line no-alert
								alert(
									JSON.stringify({
										input,
										radio,
										select,
										tags
									})
								);
							}}>
							Hi from Showcase!
						</DBButton>
					</fieldset>
				</form>
			</div>
			<div>
				<h2>Output</h2>
				<dl>
					<dt>inputs value</dt>
					<dd>{input || 'No Input set'}</dd>
					<dt>date inputs value</dt>
					<dd>{dateinput || 'No date input set'}</dd>
					<dt>textarea values</dt>
					<dd>{textarea || 'No Textrea set'}</dd>
					<dd>{textareaChildren || 'No Textrea set'}</dd>
					<dt>radio value</dt>
					<dd>{radio || 'No radio set'}</dd>
					<dt>checkbox (indeterminate) value</dt>
					<dd>{`checkbox ${checked[0] ? '' : 'un'}checked`}</dd>
					<dt>select value</dt>
					<dd>{select || 'No select set'}</dd>
					<dt>tags value</dt>
					<dd>{JSON.stringify(tags)}</dd>
				</dl>

				<DBDivider />

				<DBButton
					onClick={() => {
						setTabsTest(!tabsTest);
					}}>
					TabsTest
				</DBButton>
				<DBTabs>
					<DBTabList>
						<DBTab>Test 1</DBTab>
						<DBTab>Test 2</DBTab>
						{tabsTest && <DBTab>Test 3</DBTab>}
					</DBTabList>
					<DBTabPanel>Tab Panel 1</DBTabPanel>
					<DBTabPanel>Tab Panel 2</DBTabPanel>
					{tabsTest && <DBTabPanel>Tab Panel 3</DBTabPanel>}
				</DBTabs>

				<DBDivider />

				<DBAccordion>
					{accordionItems?.map((item) => (
						<DBAccordionItem key={item.key} title={item.key}>
							{item.value}
						</DBAccordionItem>
					))}
				</DBAccordion>

				<DBSelect
					id="select-test"
					value={select}
					label="Label"
					onChange={(event) => {
						setSelect(event.target.value);
					}}
					options={[
						{ label: 'Test1', value: 'Test1' },
						{ label: 'Test2', value: 'Test2' }
					]}
				/>
			</div>
		</div>
	);
};

export default FormComponent;

// showcases/vue-showcase/src/components/form/Form.vue
<script setup lang="ts">
import {
	DBButton,
	DBInput,
	DBRadio,
	DBCheckbox,
	DBSelect,
	DBTag,
	DBTextarea
} from "../../../../../output/vue/src";

import { ref } from "vue";
const input = ref("");
const select = ref("");
const firstInput = ref("");
const textareavModel = ref("default value");
const textarea = ref("default value");
const textareaDefaultValue = ref("");
const dateInput = ref("");
const radio = ref<HTMLInputElement>();
const checkbox = ref<boolean[]>([true, false]);
const tags = ref<string[]>([]);

const array = ["X", "Y", "Z"];

const dataList = [{ key: "test", value: "Test" }, { key: "test2" }];

const changeTags = (tag: string) => {
	if (tags.value.includes(tag)) {
		tags.value = tags.value.filter((t) => t !== tag);
	} else {
		tags.value = [...tags.value, tag];
	}
};

// eslint-disable-next-line no-alert
const logAll = () => {
	alert(
		JSON.stringify({
			input: firstInput.value,
			textarea: textarea.value,
			textareaDefaultValue: textareaDefaultValue.value,
			textareavModel: textareavModel.value,
			dateinput: dateInput.value,
			radio: radio.value,
			select: select.value,
			checkbox: checkbox.value,
			tags: tags.value
		})
	);
};

const reset = () => {
	firstInput.value = "resetted";
	textarea.value = "resetted";
	textareavModel.value = "resetted";
	checkbox.value = [true, false];
	dateInput.value = "";
};
</script>

<template>
	<div class="form-container">
		<div>
			<form>
				<fieldset>
					<p>Input:</p>
					<DBInput
						label="Textinput"
						placeholder="Placeholder"
						message="Description"
						icon="account"
						name="input-name"
						:dataList="dataList"
						v-model:value="firstInput"
					/>
					<DBInput
						label="Dateinput"
						message="Description"
						name="date-name"
						v-model:value="dateInput"
						type="date"
					/>
					<p>Textarea:</p>
					<DBTextarea
						label="Textarea v-model"
						placeholder="Placeholder"
						message="Description"
						icon="account"
						name="textarea-name"
						v-model:value="textareavModel"
					/>
					<DBTextarea
						label="Textarea value"
						placeholder="Placeholder"
						message="Description"
						icon="account"
						name="textarevalue-name"
						:value="textarea"
						@change="textarea = $event.target.value"
					/>
					<p>Radio:</p>
					<ul>
						<li v-for="radioName in array">
							<DBRadio
								@change="radio = radioName"
								name="radio-group"
								:value="radioName"
								>Radio {{ radioName }}</DBRadio
							>
						</li>
					</ul>
					<p>Tags:</p>
					<ul>
						<li v-for="(tag, index) in array">
							<DBTag
								:semantic="
									index === 0 ? undefined : 'successful'
								"
								:emphasis="index === 2 ? 'strong' : 'weak'"
								><DBCheckbox @Change="changeTags(tag)"
									>Tag {{ tag }}</DBCheckbox
								></DBTag
							>
						</li>
					</ul>
					<p>Checkbox:</p>
					<DBCheckbox
						@change="
							checkbox = [
								$event.target.checked,
								$event.target.checked
							]
						"
						:checked="checkbox[0] && checkbox[1]"
						:indeterminate="checkbox[0] !== checkbox[1]"
						name="checkbox"
						>Checkbox</DBCheckbox
					>
					<fieldset>
						<DBCheckbox
							name="checkbox-1"
							value="Checkbox checked"
							@change="
								checkbox = [$event.target.checked, checkbox[1]]
							"
							:checked="checkbox[0]"
						>
							Checkbox
						</DBCheckbox>
						<DBCheckbox
							name="checkbox-2"
							value="Checkbox checked"
							@change="
								checkbox = [checkbox[0], $event.target.checked]
							"
							:checked="checkbox[1]"
						>
							Checkbox
						</DBCheckbox>
					</fieldset>
					<p>DBSelect:</p>
					<DBSelect
						:value="select"
						label="Label"
						@change="(event) => (select = event.target.value)"
					>
						<option value="test1">Test1</option>
						<option value="test2">Test2</option>
					</DBSelect>
					<p>Button:</p>
					<DBButton type="button" @click="reset()">
						Reset Form
					</DBButton>
					<DBButton type="button" variant="brand" @click="logAll()">
						Hi from Showcase!
					</DBButton>
				</fieldset>
			</form>
		</div>
		<div>
			<h2>Output</h2>
			<dl>
				<dt>inputs value</dt>
				<dd>{{ firstInput ? firstInput : "No Input set" }}</dd>
				<dt>date inputs value</dt>
				<dd>{{ dateInput ? dateInput : "No Date Input set" }}</dd>
				<dt>textarea v-model</dt>
				<dd>{{ textareavModel || "No Input set" }}</dd>
				<dt>textarea value</dt>
				<dd>{{ textarea || "No Textarea set" }}</dd>
				<dt>textarea defaultValue</dt>
				<dd>{{ textareaDefaultValue || "No Input set" }}</dd>
				<dt>radio value</dt>
				<dd>{{ radio ? radio : "No radio set" }}</dd>
				<dt>checkbox value</dt>
				<dd>{{ `checkbox ${checkbox ? "" : "un"}checked` }}</dd>
				<dt>select value</dt>
				<dd>{{ select ? select : "No select set" }}</dd>
				<dt>tags value</dt>
				<dd>{{ JSON.stringify(tags) }}</dd>
			</dl>
		</div>
	</div>
</template>
