// showcases/angular-showcase/src/app/components/default.component.ts
import {
	Component,
	Input,
	NO_ERRORS_SCHEMA,
	type OnInit,
	type TemplateRef
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import {
	COLOR,
	COLOR_CONST,
	DBCard,
	DBDivider,
	DBLink,
	DENSITY,
	DENSITY_CONST
} from '../../../../../output/angular/src';
import type {
	DefaultComponentProps,
	DefaultComponentVariants
} from '../../../../shared/default-component-data';

@Component({
	selector: 'app-default-component',
	templateUrl: './default.component.html',
	imports: [DBCard, DBDivider, DBLink, NgTemplateOutlet],
	standalone: true,
	schemas: [NO_ERRORS_SCHEMA]
})
export class DefaultComponent implements OnInit {
	@Input() title: DefaultComponentProps['title'] = '';
	@Input() variants: DefaultComponentProps['variants'] = [];
	@Input() exampleTemplate!: TemplateRef<any>;

	density = DENSITY.REGULAR;
	color = COLOR.NEUTRAL_BG_LEVEL_1;
	page?: string;

	variantRef: DefaultComponentVariants | undefined;
	variantRefIndex = 0;

	constructor(private readonly route: ActivatedRoute) {}

	ngOnInit(): void {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters[DENSITY_CONST]) {
				this.density = parameters[DENSITY_CONST];
			}

			if (parameters['page']) {
				this.page = parameters['page'];

				const foundVariant = this.variants.find(
					(variant) => variant.name.toLowerCase() === this.page
				);

				this.variantRef = foundVariant;
				if (foundVariant) {
					this.variantRefIndex = this.variants.indexOf(foundVariant);
				}
			}

			if (parameters[COLOR_CONST]) {
				this.color = parameters[COLOR_CONST];
			}
		});
	}

	getLink = (variantName: string) => {
		let currentUrl = window.location.href;
		if (!currentUrl.includes('?')) {
			currentUrl += '?';
		}

		if (!currentUrl.includes('color=')) {
			currentUrl += `&color=${this.color || COLOR.NEUTRAL_BG_LEVEL_1}`;
		}

		if (!currentUrl.includes('density=')) {
			currentUrl += `&density=${this.density || DENSITY.REGULAR}`;
		}

		return `${currentUrl}&page=${variantName.toLowerCase()}`;
	};

	getElevation = (): '1' | '2' | '3' =>
		this.color?.includes('3') ? '3' : this.color?.includes('2') ? '2' : '1';
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<!-- TODO: Content Projection not working for nested components? -> Had to copy paste variant-cards... -->
@if (variantRef) {
	<db-card class="variants-card" [elevationLevel]="getElevation()">
		<div
			class="variants-list"
			[attr.aria-label]="variantRef.role ? variantRef.name : undefined"
			[attr.role]="variantRef.role"
		>
			@for (
				example of variantRef.examples;
				track example;
				let exampleIndex = $index
			) {
				<div
					[style]="example.style"
					[class]="example.class"
					[attr.data-density]="example.density"
				>
					<ng-container
						*ngTemplateOutlet="
							exampleTemplate;
							context: {
								exampleProps: example.props ?? {},
								exampleName: example.name,
								exampleIndex: exampleIndex,
								variantIndex: variantRefIndex
							}
						"
					>
					</ng-container>
				</div>
			}
		</div>
	</db-card>
}

@if (!variantRef) {
	<div class="default-container">
		<h1>{{ title }}</h1>
		@for (variant of variants; track variant; let variantIndex = $index) {
			<div>
				<db-divider></db-divider>
				<db-link
					class="link-headline"
					content="external"
					target="_blank"
					[href]="getLink(variant.name)"
				>
					<span>{{ variant.name }}</span>
				</db-link>

				<db-card
					class="variants-card"
					[elevationLevel]="getElevation()"
				>
					<div
						class="variants-list"
						[attr.aria-label]="
							variant.role ? variant.name : undefined
						"
						[attr.role]="variant.role"
					>
						@for (
							example of variant.examples;
							track example;
							let exampleIndex = $index
						) {
							<div
								[style]="example.style"
								[class]="example.class"
								[attr.data-density]="example.density"
							>
								<ng-container
									*ngTemplateOutlet="
										exampleTemplate;
										context: {
											exampleProps: example.props,
											exampleName: example.name,
											exampleIndex: exampleIndex,
											variantIndex: variantIndex
										}
									"
								>
								</ng-container>
							</div>
						}
					</div>
				</db-card>
			</div>
		}
	</div>
}

// showcases/react-showcase/src/components/default-component.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import React, { useCallback, useState } from 'react';
import { DBCard, DBDivider, DBLink } from '../../../../output/react/src';
import useQuery from '../hooks/use-query';
import type {
	ReactDefaultComponentProps,
	ReactDefaultComponentVariants
} from '../../../shared/react-default-component-data';

const redirectURLSearchParams = process?.env?.REDIRECT_URL_SEARCH_PARAMS
	? process.env.REDIRECT_URL_SEARCH_PARAMS === 'true'
	: true;

const VariantList = ({
	name,
	examples,
	color,
	role,
	SlotCode
}: ReactDefaultComponentVariants) => {
	const getElevation = useCallback(
		() => (color?.includes('3') ? '3' : color?.includes('2') ? '2' : '1'),
		[color]
	);

	const [open, setOpen] = useState<boolean>();

	const validExamples = examples.filter(
		(example) => redirectURLSearchParams || !example.experimental
	);

	return (
		<DBCard
			className="variants-card db-code-docs"
			elevationLevel={getElevation()}>
			<div
				role={role}
				aria-label={role ? name : undefined}
				className="variants-list">
				{validExamples.map((example, exampleIndex) => (
					<div
						key={`${example.name}-${exampleIndex}`}
						style={example.style}
						className={example.className}
						data-density={example.density}>
						{example.example}
					</div>
				))}
			</div>

			{SlotCode && (
				<details
					className="code-details"
					onToggle={() => {
						setOpen(!open);
					}}>
					<summary
						className="db-button code-button"
						data-size="small"
						data-variant="filled">
						{open ? 'Hide code' : 'Show code'}
					</summary>
					<div data-density="functional">
						<div className="backdrop" />
						<DBCard className="code" spacing="small">
							<SlotCode />
						</DBCard>
					</div>
				</details>
			)}
		</DBCard>
	);
};

const DefaultComponent = ({
	title,
	variants,
	subComponent,
	isSubComponent,
	componentName
}: ReactDefaultComponentProps) => {
	const pageName = useQuery(redirectURLSearchParams)[4];
	const color = useQuery(redirectURLSearchParams)[2];

	const getHref = (variantName: string): string => {
		if (typeof globalThis !== 'undefined') {
			const searchParams = new URLSearchParams(
				globalThis?.location?.href.split('?')[1]
			);
			searchParams.set('page', variantName.toLowerCase());
			return `${globalThis?.location?.href.split('?')[0]}?${searchParams.toString()}`;
		}

		return '';
	};

	const openVariantInNewWindow = (
		event: React.MouseEvent<HTMLAnchorElement>,
		variantName: string
	) => {
		if (
			typeof globalThis === 'undefined' ||
			!globalThis.location.origin ||
			!globalThis.location.href
		) {
			return;
		}

		const currentUrl = globalThis.location.href.split('?');
		const rawComponentUrl = currentUrl[0];
		const searchParams = new URLSearchParams(currentUrl[1] ?? '');
		searchParams.set('page', variantName.toLowerCase());

		const regexComponentOverviewFragment = /\/[a-z\d\-_]*\/overview/;

		const openUrl = componentName
			? `${rawComponentUrl.replace(regexComponentOverviewFragment, `/${componentName}/overview`)}?${searchParams.toString()}`
			: `${currentUrl[0]}?${searchParams.toString()}`;

		window.open(openUrl, '_blank');
	};

	if (pageName) {
		const foundVariant = variants.find(
			(variant) => variant.name.toLowerCase() === pageName
		);
		if (foundVariant) {
			return <VariantList {...foundVariant} color={color} />;
		}
	}

	const HeadlineTag = isSubComponent ? 'h2' : 'h1';

	return (
		<>
			<div className="default-container">
				<HeadlineTag>{title}</HeadlineTag>
				{variants
					?.filter(
						(variant) =>
							redirectURLSearchParams ||
							variant.examples.find(
								(example) => !example.experimental
							)
					)
					.map((variant, index) => (
						<div key={`${variant.name}-${index}`}>
							<DBDivider></DBDivider>
							<DBLink
								className="link-headline"
								content="external"
								target="_blank"
								onClick={(event) => {
									openVariantInNewWindow(event, variant.name);
								}}
								href={getHref(variant.name)}>
								{variant.name}
							</DBLink>
							<VariantList {...variant} color={color} />
						</div>
					))}
			</div>
			{subComponent}
		</>
	);
};

export default DefaultComponent;
