// showcases/react-showcase/src/components/accordion-item/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBAccordionItem } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/accordion-item.json';
import type { DBAccordionItemProps } from '../../../../../output/react/src/components/accordion-item/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getAccordionItem = ({
	children,
	disabled,
	open,
	headlinePlain
}: DBAccordionItemProps & { open: boolean }) => {
	return (
		<DBAccordionItem
			headlinePlain={headlinePlain}
			disabled={disabled}
			defaultOpen={open}>
			{children}
		</DBAccordionItem>
	);
};

const AccordionItemComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBAccordionItem"
			isSubComponent={props.isSubComponent}
			componentName={props.componentName}
			variants={getVariants(
				defaultComponentVariants,
				getAccordionItem,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default AccordionItemComponent;

// showcases/vue-showcase/src/components/accordion-item/AccordionItem.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/accordion-item.json";
import { DBAccordionItem } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent
		title="DBAccordionItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBAccordionItem
				:headlinePlain="exampleProps?.headlinePlain"
				:disabled="exampleProps?.disabled"
				:default-open="exampleProps?.open"
			>
				{{ exampleName }}
			</DBAccordionItem>
		</template>
	</DefaultComponent>
</template>
