// showcases/angular-showcase/src/app/components/accordion/accordion.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
	DBAccordion,
	DBAccordionItem,
	DBInfotext
} from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/accordion.json';
import { DefaultComponent } from '../default.component';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-accordion',
	templateUrl: './accordion.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBInfotext, DBAccordion, DBAccordionItem],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AccordionComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBAccordion"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
		><ng-container>
			<db-infotext size="small" semantic="informational" icon="none">
				{{ exampleName }}
			</db-infotext>
			<db-accordion
				[behaviour]="exampleProps?.behaviour"
				[variant]="exampleProps?.variant"
			>
				<db-accordion-item
					[headlinePlain]="'Item 1'"
					text="Content 1"
				></db-accordion-item>
				<db-accordion-item
					[headlinePlain]="'Item 2'"
					text="Content 2"
				></db-accordion-item>
				<db-accordion-item
					[headlinePlain]="'Item 3'"
					text="Content 3"
				></db-accordion-item>
			</db-accordion>
		</ng-container>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/accordion/Accordion.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/accordion.json";
import {
	DBAccordion,
	DBAccordionItem,
	DBInfotext
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBAccordion" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext size="small" semantic="informational" icon="none">
				{{ exampleName }}
			</DBInfotext>
			<DBAccordion
				:behaviour="exampleProps?.behaviour"
				:variant="exampleProps?.variant"
			>
				<DBAccordionItem headlinePlain="Item 1" text="Content 1" />
				<DBAccordionItem headlinePlain="Item 2" text="Content 2" />
				<DBAccordionItem headlinePlain="Item 3" text="Content 3" />
			</DBAccordion>
		</template>
	</DefaultComponent>
</template>
