// showcases/vue-showcase/src/components/header/Header.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/header.json";
import {
	DBBrand,
	DBButton,
	DBHeader,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBHeader" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBHeader
				:width="exampleProps?.width"
				:force-mobile="exampleProps?.forceMobile"
			>
				<template v-slot:brand>
					<DBBrand>
						<template
							v-if="
								!exampleProps?.example || exampleProps?.withName
							"
						>
							DBHeader
						</template>
					</DBBrand>
				</template>
				<template
					v-if="
						!exampleProps?.example || exampleProps?.withNavigation
					"
				>
					<DBNavigation :aria-label="exampleName">
						<DBNavigationItem icon="x_placeholder">
							<a href="#">{{ exampleName }}</a>
						</DBNavigationItem>
						<DBNavigationItem :disabled="true">
							<a href="#">{{ exampleName }} disabled</a>
						</DBNavigationItem>
					</DBNavigation>
				</template>
				<template v-slot:primary-action>
					<template v-if="!exampleProps?.example">
						<DBButton
							icon="magnifying_glass"
							variant="ghost"
							:no-text="true"
						>
							Search
						</DBButton></template
					>
				</template>
				<template v-slot:secondary-action>
					<template v-if="!exampleProps?.example">
						<DBButton
							icon="x_placeholder"
							variant="ghost"
							:no-text="true"
						>
							Profile
						</DBButton>
						<DBButton
							icon="x_placeholder"
							variant="ghost"
							:no-text="true"
						>
							Notification
						</DBButton>
						<DBButton
							icon="x_placeholder"
							variant="ghost"
							:no-text="true"
						>
							Help
						</DBButton></template
					>
				</template>
				<template v-slot:meta-navigation>
					<template v-if="!exampleProps?.example">
						<DBLink href="#">Imprint</DBLink>
						<DBLink href="#">Help</DBLink></template
					>
				</template>
			</DBHeader>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/header/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import {
	DBBrand,
	DBButton,
	DBHeader,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from '../../../../../output/react/src';
import { type DBHeaderProps } from '../../../../../output/react/src/components/header/model';
import defaultComponentVariants from '../../../../shared/header.json';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';
import { type BaseComponentProps } from '../base-component-data';

const getHeader = ({
	drawerOpen,
	forceMobile,
	burgerMenuLabel,
	children,
	className,
	describedbyid,
	id,
	key,
	onToggle,
	width,
	example,
	withNavigation,
	withName
}: DBHeaderProps & {
	example: boolean;
	withName: boolean;
	withNavigation: boolean;
}) => (
	<DBHeader
		width={width}
		brand={
			<DBBrand title="DBHeader">
				{(!example || withName) && 'DBHeader'}
			</DBBrand>
		}
		metaNavigation={
			!example && (
				<>
					<DBLink href="#">Imprint</DBLink>
					<DBLink href="#">Help</DBLink>
				</>
			)
		}
		primaryAction={
			!example && (
				<DBButton icon="magnifying_glass" variant="ghost" noText>
					Search
				</DBButton>
			)
		}
		secondaryAction={
			!example && (
				<>
					<DBButton icon="x_placeholder" variant="ghost" noText>
						Profile
					</DBButton>
					<DBButton icon="x_placeholder" variant="ghost" noText>
						Notification
					</DBButton>
					<DBButton icon="x_placeholder" variant="ghost" noText>
						Help
					</DBButton>
				</>
			)
		}
		drawerOpen={drawerOpen}
		forceMobile={forceMobile}
		burgerMenuLabel={burgerMenuLabel}
		className={className}
		describedbyid={describedbyid}
		id={id}
		key={key}
		onToggle={onToggle}>
		{(!example || withNavigation) && (
			<DBNavigation aria-label={children}>
				<DBNavigationItem icon="x_placeholder">
					<a href="#">{children}</a>
				</DBNavigationItem>
				<DBNavigationItem disabled>
					<a href="#">{children} disabled</a>
				</DBNavigationItem>
			</DBNavigation>
		)}
	</DBHeader>
);

const HeaderComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBHeader"
			variants={getVariants(
				defaultComponentVariants,
				getHeader,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default HeaderComponent;
