// showcases/vue-showcase/src/components/stack/Stack.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/stack.json";
import { DBStack, DBInfotext, DBDivider } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBStack" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBStack>
				<DBInfotext size="small" icon="none" semantic="informational">
					{{ exampleName }}
				</DBInfotext>
				<DBStack
					:className="
						(exampleProps.justifyContent ?? exampleProps.alignment)
							? 'stack-container stack-show-alignment'
							: 'stack-container'
					"
					:gap="exampleProps.gap"
					:alignment="exampleProps.alignment"
					:wrap="exampleProps.wrap"
					:variant="exampleProps.variant"
					:direction="exampleProps.direction"
					:justifyContent="exampleProps.justifyContent"
				>
					<span className="dummy-component">
						<a href="#">Content 1</a>
					</span>
					<template v-if="exampleProps.variant === 'divider'"
						><DBDivider />
					</template>
					<span className="dummy-component"> Content 2 </span>
					<template v-if="exampleProps.variant === 'divider'"
						><DBDivider />
					</template>
					<span className="dummy-component"> Content 3 </span>
				</DBStack>
			</DBStack>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/stack/stack.component.ts
import { Component } from '@angular/core';
import { DefaultComponent } from '../default.component';
import defaultComponentVariants from '../../../../../shared/stack.json';
import { DBStack } from '../../../../../../output/angular/src/components/stack';
import { DBInfotext } from '../../../../../../output/angular/src/components/infotext';
import { DBDivider } from '../../../../../../output/angular/src/components/divider';

@Component({
	selector: 'app-stack',
	templateUrl: './stack.component.html',
	imports: [DefaultComponent, DBStack, DBInfotext, DBDivider],
	standalone: true
})
export class StackComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBStack"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-stack>
			<db-infotext size="small" icon="none" semantic="informational">
				{{ exampleName }}
			</db-infotext>
			<db-stack
				[className]="
					(exampleProps.justifyContent ?? exampleProps.alignment)
						? 'stack-container stack-show-alignment'
						: 'stack-container'
				"
				[gap]="exampleProps.gap"
				[alignment]="exampleProps.alignment"
				[wrap]="exampleProps.wrap"
				[variant]="exampleProps.variant"
				[direction]="exampleProps.direction"
				[justifyContent]="exampleProps.justifyContent"
			>
				<span class="dummy-component"> <a href="#">Content 1</a> </span>
				@if (exampleProps.variant === "divider") {
					<db-divider />
				}

				<span class="dummy-component"> Content 2 </span>
				@if (exampleProps.variant === "divider") {
					<db-divider />
				}

				<span class="dummy-component"> Content 3 </span>
			</db-stack>
		</db-stack>
	</ng-template>
</app-default-component>
