// showcases/react-showcase/src/components/stack/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import {
	DBStack,
	DBInfotext,
	DBDivider
} from '../../../../../output/react/src';
import defaultComponentVariants from '../../../../shared/stack.json';
import type { DBStackProps } from '../../../../../output/react/src/components/stack/model';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';
import type { BaseComponentProps } from '../base-component-data';

const getStack = ({
	children,
	gap,
	alignment,
	wrap,
	variant,
	direction,
	justifyContent
}: DBStackProps) => (
	<DBStack>
		<DBInfotext size="small" icon="none" semantic="informational">
			{children}
		</DBInfotext>
		<DBStack
			className={
				(justifyContent ?? alignment)
					? 'stack-container stack-show-alignment'
					: 'stack-container'
			}
			gap={gap}
			alignment={alignment}
			wrap={wrap}
			variant={variant}
			direction={direction}
			justifyContent={justifyContent}>
			<span className="dummy-component">
				<a href="#">Content 1</a>
			</span>
			{variant === 'divider' && <DBDivider />}
			<span className="dummy-component">Content 2</span>
			{variant === 'divider' && <DBDivider />}
			<span className="dummy-component">Content 3</span>
		</DBStack>
	</DBStack>
);

const StackComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBStack"
			variants={getVariants(
				defaultComponentVariants,
				getStack,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default StackComponent;

// showcases/vue-showcase/src/components/stack/Stack.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/stack.json";
import { DBStack, DBInfotext, DBDivider } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBStack" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBStack>
				<DBInfotext size="small" icon="none" semantic="informational">
					{{ exampleName }}
				</DBInfotext>
				<DBStack
					:className="
						(exampleProps.justifyContent ?? exampleProps.alignment)
							? 'stack-container stack-show-alignment'
							: 'stack-container'
					"
					:gap="exampleProps.gap"
					:alignment="exampleProps.alignment"
					:wrap="exampleProps.wrap"
					:variant="exampleProps.variant"
					:direction="exampleProps.direction"
					:justifyContent="exampleProps.justifyContent"
				>
					<span className="dummy-component">
						<a href="#">Content 1</a>
					</span>
					<template v-if="exampleProps.variant === 'divider'"
						><DBDivider />
					</template>
					<span className="dummy-component"> Content 2 </span>
					<template v-if="exampleProps.variant === 'divider'"
						><DBDivider />
					</template>
					<span className="dummy-component"> Content 3 </span>
				</DBStack>
			</DBStack>
		</template>
	</DefaultComponent>
</template>
