// showcases/vue-showcase/src/components/tooltip/Tooltip.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tooltip.json";
import { DBButton, DBTooltip } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTooltip" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton>
				{{ exampleName }}
				<DBTooltip
					:width="exampleProps?.width"
					:emphasis="exampleProps?.emphasis"
					:placement="exampleProps?.placement"
					:animation="exampleProps?.animation"
					:delay="exampleProps?.delay"
					:variant="exampleProps?.variant"
				>
					{{ exampleProps?.content }}
				</DBTooltip>
			</DBButton>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tooltip/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBTooltip, DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/tooltip.json';
import type { DBTooltipProps } from '../../../../../output/react/src/components/tooltip/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getTooltip = ({
	children,
	width,
	emphasis,
	placement,
	delay,
	content,
	animation,
	variant
}: DBTooltipProps & { content: string }) => (
	<DBButton>
		{children}
		<DBTooltip
			width={width}
			emphasis={emphasis}
			placement={placement}
			animation={animation}
			delay={delay}
			variant={variant}>
			{content}
		</DBTooltip>
	</DBButton>
);

const TooltipComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBTooltip"
			variants={getVariants(
				defaultComponentVariants,
				getTooltip,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default TooltipComponent;
