// showcases/angular-showcase/src/app/components/home/home.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from '../../../../../../output/angular/src';
import { InputsComponent } from '../form/inputs/inputs.component';
import { FormComponent } from '../form/form.component';
import { TextareasComponent } from '../form/textareas/textareas.component';
import { SelectsComponent } from '../form/selects/selects.component';
import { CheckboxesComponent } from '../form/checkboxes/checkboxes.component';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-home',
	templateUrl: './home.component.html',
	imports: environment.webComponents
		? [
				DefaultComponent,
				InputsComponent,
				FormComponent,
				TextareasComponent,
				SelectsComponent,
				CheckboxesComponent
			]
		: [
				DBTabs,
				DBTabItem,
				DBTabList,
				DBTabPanel,
				InputsComponent,
				FormComponent,
				TextareasComponent,
				SelectsComponent,
				CheckboxesComponent
			],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class HomeComponent {}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<db-tabs data-testid="tabs">
	<db-tab-list>
		<db-tab-item>All</db-tab-item>
		<db-tab-item data-testid="tab-inputs">Input</db-tab-item>
		<db-tab-item data-testid="tab-textareas">Textarea</db-tab-item>
		<db-tab-item data-testid="tab-selects">Select</db-tab-item>
		<db-tab-item data-testid="tab-checkboxes">Checkbox</db-tab-item>
	</db-tab-list>
	<db-tab-panel>
		<app-form />
	</db-tab-panel>
	<db-tab-panel>
		<app-inputs />
	</db-tab-panel>
	<db-tab-panel>
		<app-textareas />
	</db-tab-panel>
	<db-tab-panel>
		<app-selects />
	</db-tab-panel>
	<db-tab-panel>
		<app-checkboxes />
	</db-tab-panel>
</db-tabs>

// showcases/vue-showcase/src/components/home/Home.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from "../../../../../output/vue/src";
import Form from "../form/Form.vue";
import Textareas from "../form/Textareas.vue";
import Selects from "../form/Selects.vue";
import Checkboxes from "../form/Checkboxes.vue";
import Inputs from "../form/Inputs.vue";
</script>

<template>
	<DBTabs data-testid="tabs">
		<DBTabList>
			<DBTabItem>All</DBTabItem>
			<DBTabItem data-testid="tab-inputs">Input</DBTabItem>
			<DBTabItem data-testid="tab-textareas">Textarea</DBTabItem>
			<DBTabItem data-testid="tab-selects">Select</DBTabItem>
			<DBTabItem data-testid="tab-checkboxes">Checkbox</DBTabItem>
		</DBTabList>
		<DBTabPanel>
			<Form />
		</DBTabPanel>
		<DBTabPanel>
			<Inputs />
		</DBTabPanel>
		<DBTabPanel>
			<Textareas />
		</DBTabPanel>
		<DBTabPanel>
			<Selects />
		</DBTabPanel>
		<DBTabPanel>
			<Checkboxes />
		</DBTabPanel>
	</DBTabs>
</template>
