// showcases/react-showcase/src/components/home/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from '@db-ui/react-components/src';
import FormInputs from '../form/input';
import FormComponent from '../form';
import FormTextareas from '../form/textarea';
import FormSelects from '../form/select';
import FormCheckboxes from '../form/checkbox';

const Home = () => {
	return (
		<DBTabs data-testid="tabs">
			<DBTabList>
				<DBTabItem>All</DBTabItem>
				<DBTabItem data-testid="tab-inputs">Input</DBTabItem>
				<DBTabItem data-testid="tab-textareas">Textarea</DBTabItem>
				<DBTabItem data-testid="tab-selects">Select</DBTabItem>
				<DBTabItem data-testid="tab-checkboxes">Checkbox</DBTabItem>
			</DBTabList>
			<DBTabPanel>
				<FormComponent />
			</DBTabPanel>
			<DBTabPanel>
				<FormInputs />
			</DBTabPanel>
			<DBTabPanel>
				<FormTextareas />
			</DBTabPanel>
			<DBTabPanel>
				<FormSelects />
			</DBTabPanel>
			<DBTabPanel>
				<FormCheckboxes />
			</DBTabPanel>
		</DBTabs>
	);
};

export default Home;

// showcases/vue-showcase/src/components/home/Home.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from "../../../../../output/vue/src";
import Form from "../form/Form.vue";
import Textareas from "../form/Textareas.vue";
import Selects from "../form/Selects.vue";
import Checkboxes from "../form/Checkboxes.vue";
import Inputs from "../form/Inputs.vue";
</script>

<template>
	<DBTabs data-testid="tabs">
		<DBTabList>
			<DBTabItem>All</DBTabItem>
			<DBTabItem data-testid="tab-inputs">Input</DBTabItem>
			<DBTabItem data-testid="tab-textareas">Textarea</DBTabItem>
			<DBTabItem data-testid="tab-selects">Select</DBTabItem>
			<DBTabItem data-testid="tab-checkboxes">Checkbox</DBTabItem>
		</DBTabList>
		<DBTabPanel>
			<Form />
		</DBTabPanel>
		<DBTabPanel>
			<Inputs />
		</DBTabPanel>
		<DBTabPanel>
			<Textareas />
		</DBTabPanel>
		<DBTabPanel>
			<Selects />
		</DBTabPanel>
		<DBTabPanel>
			<Checkboxes />
		</DBTabPanel>
	</DBTabs>
</template>
