// showcases/angular-showcase/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterOutlet } from '@angular/router';
import { DBSelect } from '../../../../output/angular/src/components/select/select';
import { DBMainNavigation } from '../../../../output/angular/src/components/main-navigation/main-navigation';
import { DBBrand } from '../../../../output/angular/src/components/brand/brand';
import { DBHeader } from '../../../../output/angular/src/components/header/header';
import { DBPage } from '../../../../output/angular/src/components/page/page';
import {
	COLOR,
	COLORS,
	DENSITIES,
	DENSITY,
	COLOR_CONST,
	DENSITY_CONST
} from '../../../../packages/components/src/shared/constants';
import { DBButton } from '../../../../output/angular/src/components/button';
import { ActionBarDirective } from '../../../../output/angular/src/components/header/ActionBar.directive';
import { NavigationDirective } from '../../../../output/angular/src/components/header/Navigation.directive';
import { MetaNavigationDirective } from '../../../../output/angular/src/components/header/MetaNavigation.directive';
import { NavigationContentDirective } from '../../../../output/angular/src/components/navigation-item/NavigationContent.directive';
import { NavItemComponent } from './nav-item/nav-item.component';
import {
	getSortedNavigationItems,
	NAVIGATION_ITEMS,
	NavItem
} from './utils/navigation-item';

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [
		FormsModule,
		RouterOutlet,
		NavItemComponent,
		DBPage,
		DBHeader,
		DBBrand,
		DBMainNavigation,
		DBSelect,
		DBButton,
		ActionBarDirective,
		NavigationDirective,
		MetaNavigationDirective,
		NavigationContentDirective
	],
	templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
	drawerOpen = false;
	navigationItems: NavItem[] = getSortedNavigationItems(NAVIGATION_ITEMS);

	densities = DENSITIES;
	colors = COLORS;

	density = DENSITY.REGULAR;
	color = COLOR.NEUTRAL_BG_LEVEL_1;

	page?: string;
	fullscreen = false;

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute
	) {}

	ngOnInit(): void {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters[DENSITY_CONST]) {
				this.density = parameters[DENSITY_CONST];
			}

			if (parameters[COLOR_CONST]) {
				this.color = parameters[COLOR_CONST];
			}

			if (parameters['page']) {
				this.page = parameters['page'];
			}

			if (parameters['fullscreen']) {
				this.fullscreen = parameters['fullscreen'];
			}
		});
	}

	getChangeableClasses = () => {
		return `db-density-${this.density} db-${this.color}`;
	};

	onChange = async (value: any) => {
		await this.router.navigate([], {
			relativeTo: this.route,
			queryParams: { density: this.density, color: this.color },
			queryParamsHandling: 'merge'
		});
	};

	toggleDrawer = (open: boolean) => {
		this.drawerOpen = open;
	};
}

@if (page) {
	<div [class]="getChangeableClasses()">
		<router-outlet></router-outlet>
	</div>
}
@if (!page) {
	<db-page type="fixedHeaderFooter" [fadeIn]="true">
		<db-header
			header
			[drawerOpen]="drawerOpen"
			(onToggle)="toggleDrawer($event)"
		>
			<db-brand
				brand
				title="Angular Showcase"
				src="./assets/db_logo.svg"
				href="/angular-showcase"
			>
				Showcase
			</db-brand>
			<db-main-navigation *dbNavigation>
				@for (item of navigationItems; track item.label) {
					<app-nav-item [navItem]="item"> </app-nav-item>
				}
			</db-main-navigation>
			<ng-container *dbMetaNavigation>
				<db-select
					variant="floating"
					label="Density"
					[(ngModel)]="density"
					(change)="onChange($event)"
				>
					@for (t of densities; track t) {
						<option>
							{{ t }}
						</option>
					}
				</db-select>
				<db-select
					variant="floating"
					label="Color"
					[(ngModel)]="color"
					(change)="onChange($event)"
				>
					@for (c of colors; track c) {
						<option>
							{{ c }}
						</option>
					}
				</db-select>
			</ng-container>
			<ng-container call-to-action>
				<DBButton icon="search" variant="ghost" [noText]="true"
					>Search</DBButton
				>
			</ng-container>
			<ng-container *dbActionBar>
				<DBButton icon="account" variant="ghost" [noText]="true">
					Profile
				</DBButton>
				<DBButton icon="alert" variant="ghost" [noText]="true">
					Notification
				</DBButton>
				<DBButton icon="help" variant="ghost" [noText]="true">
					Help
				</DBButton>
			</ng-container>
		</db-header>
		<div [class]="getChangeableClasses()">
			<router-outlet></router-outlet>
		</div>
	</db-page>
}

// showcases/vue-showcase/src/App.vue
<script setup lang="ts">
import {
	DBPage,
	DBHeader,
	DBBrand,
	DBSelect,
	DBMainNavigation,
	DBButton
} from "../../../output/vue/src";
import {
	COLOR,
	COLORS,
	DENSITIES,
	DENSITY,
	COLOR_CONST,
	DENSITY_CONST
} from "../../../packages/components/src/shared/constants";
import {
	getSortedNavigationItems,
	navigationItems
} from "./utils/navigation-items";

import { ref, watch, computed } from "vue";
import { useRouter, useRoute } from "vue-router";
import NavItemComponent from "./NavItemComponent.vue";

const router = useRouter();
const route = useRoute();

const density = ref(DENSITY.REGULAR);
const color = ref(COLOR.NEUTRAL_BG_LEVEL_1);
const page = ref();
const fullscreen = ref();

const drawerOpen = ref(false);

const toggleDrawer = (open: boolean) => {
	drawerOpen.value = open;
};

const classNames = computed(
	() => `db-density-${density.value} db-${color.value}`
);

const onChange = (event: any) => {
	router.push({
		path: route.path,
		query: {
			...route.query,
			[DENSITY_CONST]: density.value,
			[COLOR_CONST]: color.value
		}
	});
};

watch(
	() => route.query,
	async (query: any) => {
		if (query[COLOR_CONST] && query[COLOR_CONST] !== color.value) {
			color.value = query[COLOR_CONST];
		}
		if (query[DENSITY_CONST] && query[DENSITY_CONST] !== density.value) {
			density.value = query[DENSITY_CONST];
		}
		if (query.page) {
			page.value = query.page;
		}
		if (query.fullscreen) {
			page.value = query.fullscreen;
		}
	}
);

const sortedNavigation = getSortedNavigationItems(navigationItems);
</script>

<template>
	<div v-if="page || fullscreen" :class="classNames">
		<router-view></router-view>
	</div>
	<DBPage v-if="!page && !fullscreen" type="fixedHeaderFooter" :fadeIn="true">
		<template v-slot:header>
			<DBHeader :drawerOpen="drawerOpen" :onToggle="toggleDrawer">
				<template v-slot:brand>
					<DBBrand
						title="Showcase"
						src="db_logo.svg"
						href="/vue-showcase/"
					>
						Showcase
					</DBBrand>
				</template>
				<DBMainNavigation>
					<template v-for="item of sortedNavigation">
						<NavItemComponent :navItem="item"></NavItemComponent>
					</template>
				</DBMainNavigation>
				<template v-slot:calltoaction>
					<DBButton icon="search" variant="ghost" :no-text="true">
						Search
					</DBButton>
				</template>
				<template v-slot:actionbar>
					<DBButton icon="account" variant="ghost" :no-text="true">
						Profile
					</DBButton>
					<DBButton icon="alert" variant="ghost" :no-text="true">
						Notification
					</DBButton>
					<DBButton icon="help" variant="ghost" :no-text="true">
						Help
					</DBButton>
				</template>
				<template v-slot:metanavigation>
					<DBSelect
						label="Density"
						variant="floating"
						v-model:value="density"
						@change="onChange($event)"
					>
						<option v-for="ton of DENSITIES" :value="ton">
							{{ ton }}
						</option>
					</DBSelect>
					<DBSelect
						label="Color"
						variant="floating"
						v-model:value="color"
						@change="onChange($event)"
					>
						<option v-for="col of COLORS" :value="col">
							{{ col }}
						</option>
					</DBSelect>
				</template>
			</DBHeader>
		</template>
		<div :class="classNames">
			<router-view></router-view>
		</div>
	</DBPage>
</template>
