// showcases/angular-showcase/src/app/nav-item/nav-item.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { RouterLink, RouterLinkActive } from '@angular/router';
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import { NavItem } from '../utils/navigation-item';
import {
	DBNavigationItem,
	NavigationContentDirective
} from '../../../../../output/angular/src';
import { environment } from '../../environments/environment';

@Component({
	selector: 'app-nav-item',
	templateUrl: './nav-item.component.html',
	imports: [
		RouterLink,
		RouterLinkActive,
		DBNavigationItem,
		NavigationContentDirective
	],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	standalone: true
})
export class NavItemComponent {
	@Input({ required: true }) navItem!: NavItem;

	getBackButtonText = () => {
		return `Back to ${this.navItem.label}`;
	};
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

@if (navItem) {
	<db-navigation-item [backButtonText]="getBackButtonText()">
		@if (navItem.subNavigation) {
			<ng-container sub-navigation slot="subNavigation">
				@for (item of navItem.subNavigation; track item.label) {
					<app-nav-item [navItem]="item" />
				}
			</ng-container>
		}
		<ng-container *dbNavigationContent>
			@if (navItem.component) {
				<a
					[routerLink]="navItem.path"
					[routerLinkActiveOptions]="{ exact: true }"
					ariaCurrentWhenActive="page"
					routerLinkActive="active"
					queryParamsHandling="merge"
				>
					{{ navItem.label }}
				</a>
			}
			@if (!navItem.component) {
				{{ navItem.label }}
			}
		</ng-container>
	</db-navigation-item>
}

// showcases/vue-showcase/src/NavItemComponent.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import { DBNavigationItem } from "../../../output/vue/src";
import { type NavItem } from "./utils/navigation-items";

defineProps<{
	navItem: NavItem;
}>();
</script>

<template>
	<DBNavigationItem :backButtonText="`Back to ${navItem.label}`">
		<template v-if="navItem.subNavigation" v-slot:sub-navigation>
			<template v-for="item of navItem.subNavigation">
				<NavItemComponent :navItem="item"></NavItemComponent>
			</template>
		</template>
		<router-link
			v-if="navItem.component"
			:to="navItem.path"
			ariaCurrentValue="page"
		>
			{{ navItem.label }}
		</router-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>
