// showcases/patternhub/components/navigation/nav-item.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { type NextRouter, type Router, useRouter } from 'next/router';
import Link from 'next/link';
import { DBNavigationItem } from '../../../../output/react/src';
import type { NavigationItem } from '../../data/routes';

const isRouteActive = (
	pathname: string,
	navItem: NavigationItem,
	router: NextRouter
): boolean => {
	// Route is defined by a file within subdirectory of "pages"
	if (!router.query.slug) {
		return navItem.path === router.pathname;
	}

	// Dynamic route is defined by /pages/components/[[...slug]].tsx
	const { slug } = router.query;
	const sanitizedSlug = Array.isArray(slug) ? slug : [slug];

	return navItem.path === `/components/${sanitizedSlug.join('/')}`;
};

const NavItem = ({ navItem }: { navItem: NavigationItem }) => {
	const router = useRouter();

	const isActive = isRouteActive(router.pathname, navItem, router);

	return (
		<DBNavigationItem
			backButtonText={`Back to ${navItem.label}`}
			subNavigation={
				navItem.subNavigation && (
					<>
						{navItem?.subNavigation
							.filter(
								({ isHiddenInMenu }) => isHiddenInMenu !== true
							)
							.map((subItem: NavigationItem) => (
								<NavItem
									key={`router-path-${subItem.path}`}
									navItem={subItem}></NavItem>
							))}
					</>
				)
			}>
			{navItem.subNavigation ? (
				navItem.label
			) : (
				<Link
					key={`router-path-${navItem.path}`}
					href={navItem.path ?? ''}
					aria-current={isActive ? 'page' : undefined}>
					{navItem.label}
				</Link>
			)}
		</DBNavigationItem>
	);
};

export default NavItem;

// showcases/vue-showcase/src/NavItemComponent.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import { DBNavigationItem } from "../../../output/vue/src";
import { type NavItem } from "./utils/navigation-items";

defineProps<{
	navItem: NavItem;
}>();
</script>

<template>
	<DBNavigationItem :backButtonText="`Back to ${navItem.label}`">
		<template v-if="navItem.subNavigation" v-slot:sub-navigation>
			<template v-for="item of navItem.subNavigation">
				<NavItemComponent :navItem="item"></NavItemComponent>
			</template>
		</template>
		<router-link
			v-if="navItem.component"
			:to="navItem.path"
			ariaCurrentValue="page"
		>
			{{ navItem.label }}
		</router-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>
