// showcases/react-showcase/src/components/textarea/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { useState } from 'react';
import { DBTextarea } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/textarea.json';
import type { DBTextareaProps } from '../../../../../output/react/src/components/textarea/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getTextarea = ({
	cols,
	disabled,
	message,
	label,
	placeholder,
	rows,
	value,
	readOnly,
	required,
	children,
	variant,
	showLabel,
	showMessage,
	validMessage,
	validation,
	invalidMessage
}: DBTextareaProps) => {
	const [dynamicValue, setDynamicValue] = useState<string>(value);
	return (
		<DBTextarea
			cols={cols}
			disabled={disabled}
			showLabel={showLabel}
			message={message}
			label={label}
			variant={variant}
			readOnly={readOnly}
			onChange={(event) => {
				setDynamicValue(event.target.value);
			}}
			required={required}
			placeholder={placeholder ?? children}
			rows={rows}
			value={dynamicValue}
			showMessage={showMessage}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			validation={validation}
		/>
	);
};

const TextareaComponent = (props: BaseComponentProps) => {
	return (
		<>
			<DefaultComponent
				title="DBTextarea"
				variants={getVariants(
					defaultComponentVariants,
					getTextarea,
					props.slotCode
				)}></DefaultComponent>
		</>
	);
};

export default TextareaComponent;

// showcases/vue-showcase/src/components/textarea/Textarea.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/textarea.json";
import { DBCheckbox, DBInput, DBTextarea } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTextarea" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTextarea
				:cols="exampleProps?.cols"
				:disabled="exampleProps?.disabled"
				:show-label="exampleProps?.showLabel"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:readOnly="exampleProps?.readOnly"
				:label="exampleProps?.label"
				:placeholder="exampleProps?.placeholder || exampleName"
				:rows="exampleProps?.rows"
				:value="exampleProps?.value"
				:variant="exampleProps?.variant"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
			></DBTextarea>
		</template>
	</DefaultComponent>
</template>
