// showcases/vue-showcase/src/components/input/Input.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/input.json";
import {
	DBCheckbox,
	DBInput,
	LabelVariantType,
	ValueLabelType
} from "../../../../../output/vue/src";

const getDataList = (
	variant?: LabelVariantType
): string[] | ValueLabelType[] => {
	if (variant === "floating") {
		return ["Test 1", "Test 2"];
	}

	return [
		{ value: "test1", label: "Test 1" },
		{ value: "test2", label: "Test 2" }
	];
};
</script>

<template>
	<DefaultComponent title="DBInput" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInput
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:label="exampleProps?.label"
				:message="exampleProps?.message"
				:placeholder="exampleName"
				:minLength="exampleProps?.minLength"
				:required="exampleProps?.required"
				:type="exampleProps?.type"
				:disabled="exampleProps?.disabled"
				:readOnly="exampleProps?.readOnly"
				:value="exampleProps?.value"
				:icon="exampleProps?.icon"
				:iconAfter="exampleProps?.iconAfter"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
				:dataList="
					exampleProps?.dataList
						? getDataList(exampleProps?.variant)
						: undefined
				"
			></DBInput>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/input/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import {
	DBInput,
	type LabelVariantType,
	type ValueLabelType
} from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/input.json';
import { type DBInputProps } from '../../../../../output/react/src/components/input/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getDataList = (
	variant?: LabelVariantType
): string[] | ValueLabelType[] => {
	if (variant === 'floating') {
		return ['Test 1', 'Test 2'];
	}

	return [
		{ value: 'test1', label: 'Test 1' },
		{ value: 'test2', label: 'Test 2' }
	];
};

const getInput = ({
	label,
	value,
	type,
	minLength,
	required,
	disabled,
	iconAfter,
	icon,
	children,
	message,
	variant,
	readOnly,
	dataList,
	showLabel,
	showMessage,
	validMessage,
	validation,
	invalidMessage
}: DBInputProps & { dataList: boolean }) => {
	return (
		<DBInput
			label={label}
			message={message}
			placeholder={children}
			variant={variant}
			showLabel={showLabel}
			defaultValue={value}
			type={type}
			minLength={minLength}
			required={required}
			disabled={disabled}
			readOnly={readOnly}
			iconAfter={iconAfter}
			icon={icon}
			showMessage={showMessage}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			validation={validation}
			dataList={dataList ? getDataList(variant) : undefined}
		/>
	);
};

const InputComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBInput'}
			variants={getVariants(
				defaultComponentVariants,
				getInput,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default InputComponent;
