// showcases/vue-showcase/src/components/tab-item/TabItem.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-item.json";
import { DBTabItem, DBTabList } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTabItem" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTabList
				><DBTabItem
					:active="exampleProps?.active"
					:noText="exampleProps?.noText"
					:icon="exampleProps?.icon"
					:iconAfter="exampleProps?.iconAfter"
					:disabled="exampleProps?.disabled"
				>
					{{ exampleName }}
				</DBTabItem>
			</DBTabList>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tab-item/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBTabItem, DBTabList } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/tab-item.json';
import type { DBTabItemProps } from '../../../../../output/react/src/components/tab-item/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getTab = ({
	children,
	active,
	noText,
	icon,
	iconAfter,
	disabled
}: DBTabItemProps) => (
	<DBTabList>
		<DBTabItem
			active={active}
			noText={noText}
			icon={icon}
			iconAfter={iconAfter}
			disabled={disabled}>
			{children}
		</DBTabItem>
	</DBTabList>
);

const TabItemComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBTabItem"
			isSubComponent={props.isSubComponent}
			componentName={props.componentName}
			variants={getVariants(
				defaultComponentVariants,
				getTab,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default TabItemComponent;
