// showcases/vue-showcase/src/components/card/Card.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/card.json";
import { DBCard } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBCard" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCard
				:behaviour="exampleProps?.behaviour"
				:elevationLevel="exampleProps?.elevationLevel"
				:spacing="exampleProps?.spacing"
			>
				<strong>{{ exampleName }}</strong>
			</DBCard>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/card/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBCard } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/card.json';
import { getVariants } from '../data';
import type { DBCardProps } from '../../../../../output/react/src/components/card/model';
import { type BaseComponentProps } from '../base-component-data';

const getCard = ({
	behaviour,
	children,
	spacing,
	elevationLevel
}: DBCardProps) => (
	<DBCard
		behaviour={behaviour}
		spacing={spacing}
		elevationLevel={elevationLevel}>
		<strong>{children}</strong>
	</DBCard>
);

const CardComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBCard'}
			variants={getVariants(
				defaultComponentVariants,
				getCard,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default CardComponent;
