// showcases/angular-current-showcase/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html'
})
export class AppComponent {
	title = 'angular-current-showcase';

	tabs = [
		{
			name: 'tab-bar-2',
			label: '2-Tab1',
			active: true,
			children: 'Content 2-1'
		},
		{ name: 'tab-bar-2', label: '2-Tab2', content: 'Content 2-2' }
	];
}

<main>
	<h1>Angular</h1>
	<DBCard>
		<div style="display: flex; gap: 4px; align-items: center">
			<DBButton variant="secondary">Test</DBButton>
			<DBButton text="Test" icon="account"></DBButton>
			<DBIcon icon="account"></DBIcon>

			<section class="db-ui-expressive">
				<DBInput></DBInput>
			</section>

			<section class="db-ui-regular">
				<DBInput></DBInput>
			</section>

			<section class="db-ui-functional">
				<DBInput></DBInput>
			</section>
		</div>
	</DBCard>
</main>

// showcases/react-showcase/src/app.tsx
import { DBButton, DBIcon, DBCard, DBDivider } from '../../../output/react/src';

const App = () => (
	<main>
		<h1>React</h1>
		<DBCard>
			<div
				style={{
					display: 'flex',
					gap: '4px',
					alignItems: 'stretch'
				}}>
				<DBDivider variant="vertical" />
				<DBButton variant="secondary">Test</DBButton>
				<DBDivider variant="vertical" />
				<DBButton text="Test" icon="account" />
				<DBIcon className="icon" icon="account" />
			</div>
		</DBCard>
	</main>
);

export default App;
