// showcases/angular-showcase/src/app/components/divider/divider.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/divider.json';
import { DefaultComponent } from '../default.component';
import { DBDivider, DBInfotext } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-divider',
	templateUrl: './divider.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBDivider, DBInfotext],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class DividerComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBDivider"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-infotext size="small" semantic="informational">
			{{ exampleName }}</db-infotext
		>
		<db-divider
			[variant]="exampleProps?.variant"
			[emphasis]="exampleProps?.emphasis"
			[width]="exampleProps?.width"
		>
		</db-divider>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/divider/Divider.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/divider.json";
import { DBDivider, DBInfotext } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBDivider" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext size="small" semantic="informational">
				{{ exampleName }}</DBInfotext
			>
			<DBDivider
				:variant="exampleProps?.variant"
				:emphasis="exampleProps?.emphasis"
				:width="exampleProps?.width"
			/>
		</template>
	</DefaultComponent>
</template>
