// showcases/angular-showcase/src/app/components/link/link.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/link.json';
import { DefaultComponent } from '../default.component';
import { DBLink } from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-link',
	templateUrl: './link.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBLink],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class LinkComponent {
	variants = defaultComponentVariants;
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBLink"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-link
			[variant]="exampleProps?.variant"
			[href]="exampleProps?.href"
			[disabled]="exampleProps?.disabled"
			[size]="exampleProps?.size"
			[content]="exampleProps?.content"
			[showIcon]="exampleProps?.showIcon"
			>{{ exampleName }}</db-link
		>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/link/Link.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/link.json";
import { DBLink } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBLink" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBLink
				:variant="exampleProps?.variant"
				:href="exampleProps?.href"
				:disabled="exampleProps?.disabled"
				:size="exampleProps?.size"
				:content="exampleProps?.content"
				:showIcon="exampleProps?.showIcon"
			>
				{{ exampleName }}
			</DBLink>
		</template>
	</DefaultComponent>
</template>
