// showcases/angular-showcase/src/app/components/notification/notification.component.ts
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBLink, DBNotification } from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/notification.json';
import { DefaultComponent } from '../default.component';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-notification',
	templateUrl: './notification.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBNotification, DBLink],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	standalone: true
})
export class NotificationComponent {
	variants = defaultComponentVariants;

	showNotification = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBNotification"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-notification
			[semantic]="exampleProps?.semantic"
			[headline]="exampleProps?.headline"
			[linkVariant]="exampleProps?.linkVariant"
			[icon]="exampleProps?.icon"
			[closeable]="exampleProps?.closeable"
			[variant]="exampleProps?.variant"
			[showIcon]="exampleProps?.showIcon"
			[showHeadline]="exampleProps?.showHeadline"
			[timestamp]="exampleProps?.timestamp"
			[showTimestamp]="exampleProps?.showTimestamp"
			(onClose)="showNotification(exampleName)"
		>
			@if (exampleProps?.link) {
				<db-link link slot="link" href="#">Textlink</db-link>
			}
			@if (exampleProps?.img) {
				<img
					image
					slot="image"
					src="./assets/images/placeholder.jpg"
					alt="this is a fancy placeholder"
				/>
			}
			{{ exampleName }}
		</db-notification>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/notification/Notification.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/notification.json";
import { DBNotification, DBLink } from "../../../../../output/vue/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-notification
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent
		title="DBNotification"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBNotification
				:semantic="exampleProps?.semantic"
				:headline="exampleProps?.headline"
				:variant="exampleProps?.variant"
				:link-variant="exampleProps?.linkVariant"
				:timestamp="exampleProps?.timestamp"
				:icon="exampleProps?.icon"
				:closeable="exampleProps?.closeable"
				:showIcon="exampleProps?.showIcon"
				:showHeadline="exampleProps?.showHeadline"
				:showTimestamp="exampleProps?.showTimestamp"
				@onClose="log(exampleName)"
			>
				<template v-if="exampleProps?.link" v-slot:link>
					<DBLink href="#">Textlink</DBLink>
				</template>
				<template v-if="exampleProps?.img" v-slot:image>
					<img
						src="/assets/images/placeholder.jpg"
						alt="this is a fancy placeholder"
					/>
				</template>
				{{ exampleName }}
			</DBNotification>
		</template>
	</DefaultComponent>
</template>
