// showcases/react-showcase/src/components/notification/index.tsx
// SPDX-FileCopyrightText: 2025 DB Systel GmbH
//
// SPDX-License-Identifier: Apache-2.0

import { DBNotification, DBLink } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/notification.json';
import { type DBNotificationProps } from '../../../../../output/react/src/components/notification/model';
import { getVariants } from '../data';
import { getBasePath } from '../../utils/base-path';
import { type BaseComponentProps } from '../base-component-data';

const getNotification = ({
	semantic,
	icon,
	headline,
	variant,
	children,
	closeable,
	link,
	timestamp,
	linkVariant,
	img,
	showIcon,
	showHeadline,
	showTimestamp
}: DBNotificationProps & { link: boolean; img: boolean }) => (
	<DBNotification
		semantic={semantic}
		icon={icon}
		headline={headline}
		link={link ? <DBLink href="#">Textlink</DBLink> : undefined}
		image={
			img ? (
				<img
					src={`${getBasePath()}/assets/images/placeholder.jpg`}
					alt="this is a fancy placeholder"
				/>
			) : undefined
		}
		variant={variant}
		closeable={closeable}
		linkVariant={linkVariant}
		timestamp={timestamp}
		showTimestamp={showTimestamp}
		onClose={() => {
			// eslint-disable-next-line no-alert
			alert(children.toString());
		}}
		showIcon={showIcon}
		showHeadline={showHeadline}>
		{children}
	</DBNotification>
);

const NotificationComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBNotification"
			variants={getVariants(
				defaultComponentVariants,
				getNotification,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default NotificationComponent;

// showcases/vue-showcase/src/components/notification/Notification.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/notification.json";
import { DBNotification, DBLink } from "../../../../../output/vue/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-notification
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent
		title="DBNotification"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBNotification
				:semantic="exampleProps?.semantic"
				:headline="exampleProps?.headline"
				:variant="exampleProps?.variant"
				:link-variant="exampleProps?.linkVariant"
				:timestamp="exampleProps?.timestamp"
				:icon="exampleProps?.icon"
				:closeable="exampleProps?.closeable"
				:showIcon="exampleProps?.showIcon"
				:showHeadline="exampleProps?.showHeadline"
				:showTimestamp="exampleProps?.showTimestamp"
				@onClose="log(exampleName)"
			>
				<template v-if="exampleProps?.link" v-slot:link>
					<DBLink href="#">Textlink</DBLink>
				</template>
				<template v-if="exampleProps?.img" v-slot:image>
					<img
						src="/assets/images/placeholder.jpg"
						alt="this is a fancy placeholder"
					/>
				</template>
				{{ exampleName }}
			</DBNotification>
		</template>
	</DefaultComponent>
</template>
